"""changes

Revision ID: 95d4f1b25133
Revises: 0dd65de301d4
Create Date: 2021-11-08 12:13:33.488376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d4f1b25133'
down_revision = '0dd65de301d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
