"""user date object

Revision ID: c3904eaeca5d
Revises: 95d4f1b25133
Create Date: 2021-11-08 19:27:36.677441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3904eaeca5d'
down_revision = '95d4f1b25133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###
